version: 0.1
required_trunk_version: ">=1.11.2-beta.19"
# ThenChange tests/repo_tests/config_check.test.ts

environments:
  - name: SYSTEM
    environment:
      - name: PATH
        list: ["${env.PATH:-}"]
