version: 0.1
required_trunk_version: ">0.17.0"
lint:
  files:
    - name: dml
      extensions:
        - dml
      comments:
        - dashes-inline
        - slashes-block

    - name: ddl
      extensions:
        - ddl
      comments:
        - dashes-inline
        - slashes-block
