version: 0.1
lint:
  definitions:
    - name: pre-commit-hooks
      known_good_version: 4.4.0
      runtime: python
      package: pre-commit-hooks
      environment:
        - name: PATH
          list: ["${env.PATH}"]
      commands:
        - name: check-added-large-files
          output: pass_fail
          read_output_from: stdout
          run: check-added-large-files ${target}
          success_codes: [0, 1]
          files:
            - ALL
        - name: check-ast
          output: pass_fail
          read_output_from: stdout
          run: check-ast ${target}
          success_codes: [0, 1]
          files:
            - python
        - name: check-builtin-literals
          output: pass_fail
          read_output_from: stdout
          run: check-builtin-literals ${target}
          success_codes: [0, 1]
          files:
            - python
        - name: check-case-conflict
          output: pass_fail
          read_output_from: stdout
          run: check-case-conflict ${target}
          success_codes: [0, 1]
          files:
            - ALL
        - name: check-docstring-first
          output: pass_fail
          read_output_from: stdout
          run: check-docstring-first ${target}
          success_codes: [0, 1]
          files:
            - python
        - name: check-json
          output: pass_fail
          read_output_from: stdout
          run: check-json ${target}
          success_codes: [0, 1]
          files:
            - json
        - name: check-merge-conflict
          output: pass_fail
          read_output_from: stdout
          run: check-merge-conflict ${target}
          success_codes: [0, 1]
          files:
            - ALL
        - name: check-shebang-scripts-are-executable
          output: pass_fail
          read_output_from: stderr
          run: check-shebang-scripts-are-executable ${target}
          success_codes: [0, 1]
          files:
            - ALL
        - name: check-symlinks
          output: pass_fail
          read_output_from: stderr
          run: check-symlinks ${target}
          success_codes: [0, 1]
          files:
            - ALL
        - name: check-toml
          output: pass_fail
          read_output_from: stderr
          run: check-toml ${target}
          success_codes: [0, 1]
          files:
            - toml
        - name: check-vcs-permalinks
          output: pass_fail
          read_output_from: stderr
          run: check-vcs-permalinks ${target}
          success_codes: [0, 1]
          files:
            - ALL
        - name: check-xml
          output: pass_fail
          read_output_from: stderr
          run: check-xml ${target}
          success_codes: [0, 1]
          files:
            - xml
        - name: check-yaml
          output: pass_fail
          read_output_from: stderr
          run: check-yaml ${target}
          success_codes: [0, 1]
          files:
            - yaml
        - name: debug-statement-hook
          output: pass_fail
          read_output_from: stderr
          run: debug-statement-hook ${target}
          success_codes: [0, 1]
          files:
            - python
        - name: destroyed-symlinks
          output: pass_fail
          read_output_from: stderr
          run: destroyed-symlinks ${target}
          success_codes: [0, 1]
          files:
            - ALL
        - name: detect-private-key
          output: pass_fail
          read_output_from: stderr
          run: detect-private-key ${target}
          success_codes: [0, 1]
          files:
            - ALL
        - name: end-of-file-fixer
          output: rewrite
          in_place: true
          formatter: true
          run: end-of-file-fixer ${target}
          success_codes: [0, 1]
          files:
            - ALL
        - name: mixed-line-ending
          output: pass_fail
          read_output_from: stdout
          run: mixed-line-ending --fix=no ${target}
          success_codes: [0, 1]
          files:
            - ALL
        - name: trailing-whitespace
          output: rewrite
          in_place: true
          formatter: true
          run: mixed-line-ending --fix=no ${target}
          success_codes: [0, 1]
          files:
            - ALL
