version: 0.1
lint:
  definitions:
    - name: prisma
      tools: [prisma]
      files: [prisma]
      known_good_version: 4.16.1
      suggest_if: never
      commands:
        - name: prisma format
          output: rewrite
          success_codes: [0]
          in_place: true
          batch: true
          formatter: true
          run: prisma format --schema=${target}
        - name: prisma validate
          run: prisma validate --schema=${target}
          output: pass_fail
          batch: true
          success_codes: [0, 1]
          read_output_from: stderr
