version: 0.1
lint:
  # When enabling stylelint, you should also add the stylelint plugin configs,
  # like so:
  #
  #   lint:
  #   enabled:
  #     - stylelint@15.3.0:
  #         packages:
  #           - stylelint-config-standard@31.0.0
  #           - stylelint-config-standard-scss@7.0.1
  #
  definitions:
    - name: stylelint
      files: [css, sass]
      runtime: node
      package: stylelint
      commands:
        - name: lint
          # Custom parser type defined in the trunk cli to handle stylelint's JSON output.
          output: stylelint
          success_codes: [0, 2]
          run: stylelint -f json ${target}
        - name: fix
          formatter: true
          output: rewrite
          success_codes: [0, 2]
          run: stylelint --fix ${target}
          in_place: true
      direct_configs:
        - .stylelintrc
        - .stylelintrc.json
        - .stylelintrc.yml
        - .stylelintrc.yaml
        - .stylelintrc.js
        - .stylelintrc.cjs
      affects_cache:
        - package.json
        - .stylelintignore
      known_good_version: 14.6.1
      version_command:
        parse_regex: ${semver}
        run: stylelint --version
