name: Linter Tests
on:
  workflow_call:
    inputs:
      linter-version:
        required: false
        type: string
      cli-version:
        required: false
        type: string
      cli-path:
        required: false
        type: string
      cache-tools:
        required: false
        type: boolean
        default: true
      plugin-ref:
        required: false
        type: string
        default: ""
      path:
        required: false
        type: string
        default: $GITHUB_WORKSPACE
jobs:
  linter_tests:
    name: Linter Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ inputs.path }}
          ref: ${{ inputs.plugin-ref }}
          repository: trunk-io/plugins

      - name: Cache tool downloads
        if: inputs.cache-tools
        uses: actions/cache@v3
        with:
          path: /tmp/plugins_testing_download_cache
          # No need to key on trunk version unless we change how we store downloads.
          key: trunk-${{ runner.os }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Sync lfs
        run: git lfs pull
        working-directory: ${{ inputs.path }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.path }}

      - name: Run plugin tests
        run: |
          PATH=$(npm bin):$PATH npm test --ci linters
        working-directory: ${{ inputs.path }}
        env:
          PLUGINS_TEST_LINTER_VERSION: ${{ inputs.linter-version }}
          PLUGINS_TEST_CLI_VERSION: ${{ inputs.cli-version }}
          PLUGINS_TEST_CLI_PATH: ${{ inputs.cli-path }}
