name: Nightly
on:
  schedule:
    # Times in UTC (PST+8), this translates to running Mon-Fri at midnight/1am (depending on DST)
    - cron: 0 8 * * 1-5
  pull_request:
    paths: [.github/workflows/nightly.yaml]
  workflow_dispatch: {}

jobs:
  # Run tests against all linters for snapshots and latest version
  linter_tests:
    name: Plugin Tests
    uses: ./.github/workflows/linter_tests.yaml
    strategy:
      fail-fast: false
      matrix:
        linter-version: [Snapshots, Latest]
    with:
      linter-version: ${{ matrix.linter-version }}
      cache-tools: true
  # Run repo healthcheck tests
  repo_tests:
    name: Repo Tests
    uses: ./.github/workflows/repo_tests.yaml
